# EcoAPI Configuration

# Performance Settings
# Enable caching to improve performance by reducing database queries
# Player data will be saved to the database when they log out
use-cache: true

# Default Economy Values
# Starting balance for new players
starting-balance: 1000.0

# Starting tokens for new players
starting-tokens: 0.0

# Database Settings
# Database type (currently only sqlite is supported)
database-type: sqlite

# Format Settings
# Currency symbol to use when formatting amounts
currency-symbol: "$"

# Permissions
# economy.commands: Access to the /economy commands
# economy.commands.give: Permission to give money to others
# economy.commands.take: Permission to take money from others
# economy.commands.set: Permission to set other players' balance
# economy.commands.reset: Permission to reset player economy data
# economy.commands.info: Permission to view other players' economy data